language: node_js
node_js: stable

cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

script:
  - npm run build

after_script:
  - cd dist/
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add -A
  - git commit -m "realese version"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
  - cd -
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/f3f/visualcontrols.git
